### ISSUE TITLE
Piv manager 1.3 does not run in Xenial because of "missing" pyside dependency

### ISSUE THREAD

**Issue by lhernanz** [Yubico/yubikey-piv-manager-dpkg#1]
Hi,

pivman 1.3.0-1~ppa1~xenial1 fails with the following message:
Traceback (most recent call last):
  File "/usr/bin/pivman", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 3084, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 3070, in _call_aside
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 651, in _build_master
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 952, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 839, in resolve
pkg_resources.DistributionNotFound: The 'PySide' distribution was not found and is required by yubikey-piv-manager

The official debian package includes an specific patch to deal with this issue that seems to be missing in the PPA.

Regards.

**Comment by dagheyman** [comment]
Thank you for the report! The patch is now re-introduced and a new package for xenial is available in the PPA.
